# Generated by Django 4.2.6 on 2025-07-01 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vehicle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='آیشن')),
            ],
            options={
                'verbose_name': 'آیشن',
                'verbose_name_plural': 'آیشن ها',
            },
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'رنگ موتر',
                'verbose_name_plural': 'رنگ های موتر',
            },
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='موقعیت')),
                ('vin', models.CharField(blank=True, max_length=100, verbose_name='VIN#')),
                ('lot', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='LOT#')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.caraction', verbose_name='آیشن')),
            ],
            options={
                'verbose_name': 'معلومات جنس',
                'verbose_name_plural': 'معلومات جنس',
            },
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='مارک')),
            ],
            options={
                'verbose_name': 'مارک موتر',
                'verbose_name_plural': 'مارک های موتر',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=50, verbose_name='Currency Name')),
                ('symbol', models.CharField(max_length=5, verbose_name='Currency Symbol')),
                ('exchange_rate', models.DecimalField(decimal_places=6, help_text='1 unit of this currency equals how much in base currency', max_digits=15, verbose_name='Current Exchange Rate to Base Currency')),
                ('is_base', models.BooleanField(default=False, verbose_name='Is Base Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ModelYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='سال مدل')),
            ],
            options={
                'verbose_name': 'سال مدل',
                'verbose_name_plural': 'سال های مدل',
            },
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='مربوطیت')),
            ],
            options={
                'verbose_name': 'مربوطیت',
                'verbose_name_plural': 'مربوطیت ها',
            },
        ),
        migrations.CreateModel(
            name='WorldExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herat_arrival_date', models.DateField(blank=True, null=True, verbose_name='تاریخ رسید به هرات')),
                ('business_company_comission', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, max_digits=15, verbose_name='کمیشن شرکت تجارتی')),
                ('business_company_comission_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت کمیشن شرکت تجارتی')),
                ('has_business_company_remain_comission', models.BooleanField(default=False, verbose_name='پرداخت باقی کمیشن تجاری')),
                ('business_company_remain_comission', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='باقی کمیشن شرکت تجارتی')),
                ('business_company_remain_comission_date', models.DateField(blank=True, null=True, verbose_name='تاریخ باقی کمیشن شرکت تجارتی')),
                ('gomrok_payment', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, max_digits=15, verbose_name='محصول گمرکی')),
                ('gomrok_payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت محصول گمرکی')),
                ('has_gomrok_remain_payment', models.BooleanField(default=False, verbose_name='پرداخت باقی محصول گمرکی')),
                ('gomrok_remain_payment', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='باقی محصول گمرکی')),
                ('gomrok_remain_payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ باقی محصول گمرکی')),
                ('shipiping_price_to_islam_qala', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, max_digits=15, verbose_name='قیمت شیپنگ به اسلام قلعه')),
                ('shipiping_price_to_islam_qala_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت شیپنگ')),
                ('paid_value_for_shipping', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ پرداخت شده شیپنګ')),
                ('paid_value_for_shipping_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت شیپنګ')),
                ('remain_shipping_for_islam_qala', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='باقی شیپینک به اسلام قلعه')),
                ('return_date_from_dubai', models.DateField(blank=True, null=True, verbose_name='تاریخ بارگیری از دبی')),
                ('business_company_comission_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for کمیشن شرکت تجارتی')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world_expenses', to='vehicle.carinfo')),
                ('gomrok_payment_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for محصول گمرکی')),
                ('paid_value_for_shipping_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for مبلغ پرداخت شده شیپنګ')),
                ('shipiping_price_to_islam_qala_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for قیمت شیپنگ')),
            ],
            options={
                'verbose_name': 'مصارف انتقالات',
                'verbose_name_plural': 'مصارف انتقالات',
            },
            bases=(models.Model, vehicle.models.CurrencyModelMixin),
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrived_in_dubai', models.DateField(blank=True, null=True, verbose_name='تاریخ رسید به امارات')),
                ('total_price_to_dubai', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت تمام شده الی دبی ($)')),
                ('cash_paid_comission', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='کمیشن حواله پول')),
                ('cash_paid_comission_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت کمیشن حواله پول')),
                ('dubai_paid_invoice', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='مبلغ پرداخت شده انوایس دبی')),
                ('dubai_paid_invoice_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت انوایس دبی')),
                ('attstion', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ATTSTION INSSPECTION PORTCLIP$PRMI..')),
                ('attstion_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ATTSTION')),
                ('commission', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='COMISSION')),
                ('commission_date', models.DateField(blank=True, null=True, verbose_name='تاریخ COMISSION')),
                ('clearing', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='CLEARING')),
                ('clearing_date', models.DateField(blank=True, null=True, verbose_name='تاریخ CLEARING')),
                ('duty_vat', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='DUTY/VAT')),
                ('duty_vat_date', models.DateField(blank=True, null=True, verbose_name='تاریخ DUTY/VAT')),
                ('d_o', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='D/o')),
                ('d_o_date', models.DateField(blank=True, null=True, verbose_name='تاریخ D/o')),
                ('red_sea', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='RED SEA')),
                ('red_sea_date', models.DateField(blank=True, null=True, verbose_name='تاریخ RED SEA')),
                ('towing', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Towing')),
                ('towing_date', models.DateField(blank=True, null=True, verbose_name='تاریخ Towing')),
                ('shipping', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Shipping')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='تاریخ Shipping')),
                ('etd_from_usa', models.DateField(blank=True, null=True, verbose_name='ETD from USA')),
                ('cnt_number', models.CharField(blank=True, max_length=100, verbose_name='Cnt#')),
                ('bkg_number', models.CharField(blank=True, max_length=100, verbose_name='Bkg#')),
                ('port_clips_prmi', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='PORTCLIPSPRMI')),
                ('port_clips_prmi_date', models.DateField(blank=True, null=True, verbose_name='تاریخ PORTCLIPSPRMI')),
                ('attstion_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for ATTSTION')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info', to='vehicle.carinfo')),
                ('cash_paid_comission_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for کمیشن حواله پول')),
                ('clearing_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for CLEARING')),
                ('commission_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for COMISSION')),
                ('d_o_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for D/o')),
                ('dubai_paid_invoice_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for مبلغ پرداخت شده انوایس دبی')),
                ('duty_vat_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for DUTY/VAT')),
                ('port_clips_prmi_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for PORTCLIPSPRMI')),
                ('red_sea_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for RED SEA')),
                ('shipping_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for Shipping')),
                ('total_price_to_dubai_currency', models.ForeignKey(default=vehicle.models.get_usd_currency, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for قیمت تمام شده الی دبی')),
                ('towing_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for Towing')),
            ],
            options={
                'verbose_name': 'اطلاعات حمل و نقل',
                'verbose_name_plural': 'اطلاعات حمل و نقل',
            },
            bases=(models.Model, vehicle.models.CurrencyModelMixin),
        ),
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('آماده فروش', 'آماده فروش'), ('فروخته شده', 'فروخته شده'), ('در راه', 'در راه')], default='آماده فروش', max_length=20, verbose_name='حالت')),
                ('split_50_50', models.CharField(blank=True, max_length=100, verbose_name='50/50 مقدار')),
                ('buyer_remain_payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت باقی خریدار')),
                ('remaining_price_of_buyer', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, max_digits=15, verbose_name='باقی خریدار')),
                ('buyer_info', models.TextField(blank=True, verbose_name='شهریت خریدار')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='تاریخ فروش')),
                ('sale_price', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, help_text='For sold cars, enter the sale price manually. For unsold cars, it will be automatically set to the repair and other expenses final cost.', max_digits=15, verbose_name='قیمت فروش')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_info', to='vehicle.carinfo')),
                ('sale_price_currency', models.ForeignKey(default=vehicle.models.get_usd_currency, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for قیمت فروش')),
            ],
            options={
                'verbose_name': 'اطلاعات فروش',
                'verbose_name_plural': 'اطلاعات فروش',
            },
        ),
        migrations.CreateModel(
            name='RepairAndOtherExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_cost', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, max_digits=15, verbose_name='مصارف ترمیم')),
                ('repair_cost_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت ترمیم')),
                ('remaining_repair_cost', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, help_text='This should be set manually and not automatically calculated', max_digits=15, verbose_name='باقی مصارف ترمیم')),
                ('palate_cost', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, max_digits=15, verbose_name='مصارف پلیت')),
                ('palate_cost_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت پلیت')),
                ('palate_remaining_const', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, help_text='This should be set manually and not automatically calculated', max_digits=15, verbose_name='باقی مصارف پلیت')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair_expenses', to='vehicle.carinfo')),
                ('palate_cost_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for مصارف پلیت')),
                ('repair_cost_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for مصارف ترمیم')),
            ],
            options={
                'verbose_name': 'مصارف ترمیم و سایر هزینه ها',
                'verbose_name_plural': 'مصارف ترمیم و سایر هزینه ها',
            },
            bases=(models.Model, vehicle.models.CurrencyModelMixin),
        ),
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, help_text='مبلغی که برای خرید این وسیله پرداخت شده است', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ پرداخت شده قیمت خرید ($)')),
                ('purchase_price', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, help_text='قیمت کامل خرید وسیله به دالر', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرید ($)')),
                ('remain_purchase', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='باقی انوایس خرید ($)')),
                ('buy_date', models.DateTimeField(default=django.utils.timezone.now, help_text='تاریخ و زمانی که وسیله خریداری شده است', verbose_name='تاریخ و زمان خرید')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_info', to='vehicle.carinfo', verbose_name='وسیله نقلیه')),
                ('paid_amount_currency', models.ForeignKey(default=vehicle.models.get_usd_currency, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for مبلغ پرداخت شده')),
                ('purchase_price_currency', models.ForeignKey(default=vehicle.models.get_usd_currency, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for قیمت خرید')),
            ],
            options={
                'verbose_name': 'معلومات خرید',
                'verbose_name_plural': 'معلومات خرید',
            },
            bases=(models.Model, vehicle.models.CurrencyModelMixin),
        ),
        migrations.CreateModel(
            name='KabulExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herat_to_kabul_cost', vehicle.models.CurrencyAmountField(decimal_places=2, default=0, max_digits=15, verbose_name='کرایه از هرات الی کابل')),
                ('herat_to_kabul_cost_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت کرایه')),
                ('has_remaining_price_from_herat_to_kabul', models.BooleanField(default=False, verbose_name='پرداخت باقی کرایه از هرات الی کابل')),
                ('remaining_price_from_herat_to_kabul', vehicle.models.CurrencyAmountField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='باقی کرایه از هرات الی کابل')),
                ('remaining_price_from_herat_to_kabul_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('arrival_date_kabul', models.DateField(blank=True, null=True, verbose_name='تاریخ رسید به کابل')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kabul_expenses', to='vehicle.carinfo')),
                ('herat_to_kabul_cost_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Currency for کرایه از هرات الی کابل')),
            ],
            options={
                'verbose_name': 'مصارف کابل',
                'verbose_name_plural': 'مصارف کابل',
            },
            bases=(models.Model, vehicle.models.CurrencyModelMixin),
        ),
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='سیستم من', max_length=100, null=True, verbose_name='Site Name')),
                ('logo', models.ImageField(blank=True, help_text='لوگوی سیستم (ترجیحاً با پسزمینه شفاف)', null=True, upload_to='site_logos/', verbose_name='Logo')),
                ('address', models.TextField(blank=True, help_text='آدرس کامل', null=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, help_text='ایمیل تماس', max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='شماره تماس', max_length=20, null=True, verbose_name='Phone Number')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('base_currency', models.ForeignKey(blank=True, default=vehicle.models.get_usd_currency, help_text='The base currency used for all calculations', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicle.currency', verbose_name='Base Currency')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع موتر')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.carmark', verbose_name='مارک')),
            ],
            options={
                'verbose_name': 'نوع موتر',
                'verbose_name_plural': 'انواع موتر',
            },
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.cartype', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.carcolor', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.carmark', verbose_name='MARK'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='model_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.modelyear', verbose_name='مدل سال'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.related', verbose_name='مربوطیت'),
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/', verbose_name='عکس موتر')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle.carinfo', verbose_name='موتر')),
            ],
            options={
                'verbose_name': 'عکس موتر',
                'verbose_name_plural': 'عکس\u200cهای موتر',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate History',
                'verbose_name_plural': 'Exchange Rate Histories',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['currency', 'date'], name='vehicle_exc_currenc_877e97_idx')],
            },
        ),
    ]
