# Generated by Django 4.2.6 on 2025-07-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinfo',
            name='remaining_price_of_buyer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='باقی خریدار'),
        ),
        migrations.AlterField(
            model_name='saleinfo',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='For sold cars, enter the sale price manually. For unsold cars, it will be automatically set to the repair and other expenses final cost.', max_digits=12, verbose_name='قیمت فروش'),
        ),
    ]
