# Generated by Django 4.2.6 on 2025-07-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_saleinfo_remaining_price_of_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام خریدار')),
                ('contact_info', models.TextField(blank=True, verbose_name='اطلاعات تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='نمبر تذکره')),
                ('additional_info', models.TextField(blank=True, verbose_name='اطلاعات اضافی')),
            ],
            options={
                'verbose_name': 'خریدار',
                'verbose_name_plural': 'خریداران',
            },
        ),
        migrations.RemoveField(
            model_name='saleinfo',
            name='buyer_info',
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.buyer', verbose_name='خریدار'),
        ),
    ]
