# Generated by Django 4.2.6 on 2025-07-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_buyer_remove_saleinfo_buyer_info_saleinfo_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinfo',
            name='split_50_50',
        ),
    ]
