# Generated by Django 5.2.4 on 2025-07-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_remove_saleinfo_split_50_50'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinfo',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='تاریخی که باقی مانده پرداخت خواهد شد', null=True, verbose_name='تاریخ پرداخت باقی مانده'),
        ),
    ]
